name: LeafSK
description: A Skript Addon which has some usefull stuff from other addons.
main: com.leaf.Leaf
version: 2.1.0
api-version: 1.13
authors: [Tuke-Nuke,btk5h, Sashie, TheLimeGlass, Andrei923]
depend: [Skript]